name: Arduino
 
on:
  push:
    branches:
      - master
      - develop
      - main
  pull_request:
  release:
    types:
      - created
 
jobs:
  build:
    runs-on: ubuntu-latest 

    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@main
 
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
 
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli board listall
          arduino-cli core install arduino:esp32

      - name: Install libraries
        run: arduino-cli lib install "ArduinoJson"
 
      - name: Compile Sketch
        run: arduino-cli compile --fqbn esp32:esp32:esp32 examples/json
