name: Arduino
 
on: [push, pull_request]
 
jobs:
  test-matrix:
 
    strategy:
      matrix:
        arduino-platform: ["arduino:esp32"]
        include:
          - arduino-platform: "arduino:esp32"
            fqbn: "esp32:esp32:esp32"

    runs-on: windows-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@master
 
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.0.0
 
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}
 
      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./json
        