name: Arduino

on:
  push:
    branches:
      - master
      - develop
  pull_request:
  release:
    types:
      - created

jobs:
  Boards:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        board:
          - esp32:esp32:nodemcu

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install arduino-cli
        run: |
          make setup
      - name: Build
        run: |
          make setup
          make all TARGET=${{ matrix.board }}