name: Arduino
 
on:
  push:
    branches:
      - master
      - develop
      - main
  pull_request:
  release:
    types:
      - created
 
jobs:
  test-matrix:
 
    strategy:
      matrix:
        arduino-platform: ["arduino:esp32"]
        include:
          - arduino-platform: "esp32:esp32"
            fqbn: "esp32:esp32:esp32"

    runs-on: ubuntu-latest 

    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@main
 
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
 
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli board listall
          arduino-cli core install ${{ matrix.arduino-platform }}
 
      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} examples/json
